// user
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_FAILED = 'USER_LOGOUT_FAILED';
export const USER_WAITLIST = 'USER_WAITLIST';
export const USER_WAITLIST_SUCCESS = 'USER_WAITLIST_SUCCESS';
export const USER_WAITLIST_FAILED = 'USER_WAITLIST_FAILED';
export const USER_REGISTER = 'USER_REGISTER';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAILED = 'USER_REGISTER_FAILED';
export const USER_RESET = 'USER_RESET';
export const USER_RESET_SUCCESS = 'USER_RESET_SUCCESS';
export const USER_RESET_FAILED = 'USER_RESET_FAILED';
export const USER_FORGOT = 'USER_FORGOT';
export const USER_FORGOT_SENT = 'USER_FORGOT_SENT';
export const USER_FORGOT_FAILED = 'USER_FORGOT_FAILED';
export const USER_AUTH = 'USER_AUTH';
export const USER_DEAUTH = 'USER_DEAUTH';
export const USER_VERIFY = 'USER_VERIFY';

export const USER_ERROR = 'CUR_USER_ERROR';
export const USER_SUBMITTING = 'CUR_USER_SUBMITTING';

// profile
export const PROFILE_GET = 'PROFILE_GET';
export const PROFILE_GET_SUCCESS = 'PROFILE_GET_SUCCESS';
export const PROFILE_GET_FAILED = 'PROFILE_GET_FAILED';
export const PROFILE_UPDATE = 'PROFILE_UPDATE';
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS';
export const PROFILE_UPDATE_FAILED = 'PROFILE_UPDATE_FAILED';

// app
export const GOTO_PAGE = 'GOTO_PAGE';
export const APP_GOHOME = 'APP_GOHOME';
export const APP_ERROR = 'APP_ERROR';
export const APP_CONNECTED = 'APP_CONNECTED';
export const APP_RECONNECTING = 'APP_RECONNECTING';
export const APP_DISCONNECTED = 'APP_DISCONNECTED';

// snackbar
export const ENQUEUE_SNACKBAR = 'ENQUEUE_SNACKBAR';
export const DEQUEUE_SNACKBAR = 'DEQUEUE_SNACKBAR';

// drawer
export const DRAWER_TOGGLE = 'DRAWER_TOGGLE';

// modal
export const DIALOG_CLOSE = 'DIALOG_CLOSE';
export const DIALOG_OPEN = 'DIALOG_OPEN';
